apiVersion: v1
kind: Service
metadata:
  name: demo
  labels:
    app: demo
spec:
  type: ClusterIP
  selector:
    app: demo
    name: demo
  ports:
    - port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  labels:
    app: demo
spec:
  selector:
    matchLabels:
      app: demo
      name: demo
  template:
    # Pod definition starts here
    metadata:
      labels:
        app: demo
        name: demo
    spec:
      containers:
        - name: demo
          image: raymondfanglimin/demo:github.run_number