name: Pal Tracker Pipeline

on: [push]

env:
  DOCKER_HUB_USERNAME: raymondfanglimin

jobs:
  build-pack-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Startup test database instance
        run: sudo service mysql start
      - name: Create rps database and rpsuser
        run: |
          mysql -uroot -proot < db/createdb.sql
      - name: Build with Gradle
        run: ./gradlew bootBuildImage --imageName=${{env.DOCKER_HUB_USERNAME}}/demo:build-${{github.run_number}}
      - run: sudo curl -sSL https://get.docker.com/ | sh
      - run: docker login -u "${{env.DOCKER_HUB_USERNAME}}" -p "${{secrets.DOCKER_HUB_PASSWORD}}"
      - run: docker push ${{env.DOCKER_HUB_USERNAME}}/demo:build-${{github.run_number}}
  deploy:
    needs: build-pack-and-publish
    runs-on: ubuntu-latest
    steps:
      - run: curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.18.6/bin/linux/amd64/kubectl
      - run: chmod +x ./kubectl
      - uses: actions/checkout@v1
      - run: echo ${{secrets.K8S_CONFIG}} > config
      - run: grep "github.run_number" k8s/demo.yaml
      - run: sed -i 's/github.run_number/${{github.run_number}}/g' k8s/demo.yaml
      - run: kubectl apply -k k8s/demo.yaml --kubeconfig=config --insecure-skip-tls-verify